name: airflow
services:
  scheduler:
    user: root
    environment:
      PYTHONPATH: /usr/local/airflow
      AIRFLOW__DAG_PROCESSOR__DAGBAG_IMPORT_TIMEOUT: "120"
    volumes:
      - ./dbt/demodadosdw/:/usr/local/airflow/dbt/demodadosdw
      - ./dbt/my_datawarehouse:/usr/local/airflow/dbt/my_datawarehouse
      - /media/lucas/Files/2.Projetos/0.mylake:/usr/local/airflow/mylake

  dag-processor:
    user: root
    environment:
      PYTHONPATH: /usr/local/airflow
      AIRFLOW__DAG_PROCESSOR__DAGBAG_IMPORT_TIMEOUT: "120"
    volumes:
      - ./dbt/demodadosdw/:/usr/local/airflow/dbt/demodadosdw
      - ./dbt/my_datawarehouse:/usr/local/airflow/dbt/my_datawarehouse
      - /media/lucas/Files/2.Projetos/0.mylake:/usr/local/airflow/mylake
